name: Release
  uses: qcastel/github-actions-maven-release@master
  with:
    release-branch-name: "master"

    git-release-bot-name: "release-bot"
    git-release-bot-email: "martin@van-dijken.eu"

    access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}