# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
workflow_dispatch:
  inputs:
    version:
      description: 'version to release'
      required: true
      default: '0.0.1'
    next_version:
      description: 'next version after release'
      required: true
      default: '0.0.1-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B release:prepare --file pom.xml -f pom.xml -DreleaseVersion=${{ github.event.inputs.version }} -DdevelopmentVersion=${{ github.event.inputs.next_version }}
